Traceback (most recent call last):
  File "/home/xippi-xard/chat/mainChat.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
Traceback (most recent call last):
  File "/home/xippi-xard/chat/mainChat.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
Traceback (most recent call last):
  File "/home/xippi-xard/chat/mainChat.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
